# Generated by Django 4.1 on 2022-08-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_surname', models.CharField(max_length=30)),
                ('customer_dni', models.CharField(max_length=8)),
                ('dob', models.DateField()),
                ('branch_id', models.CharField(max_length=3)),
            ],
        ),
    ]
