# Generated by Django 4.1 on 2022-08-13 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0003_alter_tarjeta_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta',
            options={},
        ),
    ]
