# Generated by Django 4.1 on 2022-08-13 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('movimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_operacion', models.CharField(choices=[('EXTRACCION', 'EXTRACCION'), ('DEPOSITO', 'DEPOSITO')], max_length=10)),
                ('hora', models.TextField()),
                ('numero_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuenta')),
            ],
            options={
                'db_table': 'movimiento',
            },
        ),
    ]
