# Generated by Django 4.1 on 2022-08-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_movimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={},
        ),
        migrations.AddField(
            model_name='movimiento',
            name='monto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
